name: Python tests

on:
  pull_request:
    branches: [main, dev]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f dependencies.txt ]; then pip install -r dependencies.txt; fi
      - name: 'Create env file'
        run: |
          touch .env
          echo "db=${{ secrets.TEST_DATABASE }}" >> .env
          cat .env
      - name: Test with unittest
        run: |
          python -m unittest discover -s test -p "*_test.py"